
[
    /*----------------------------------------------------------------------------------*/
    /*-MENUS-*/
    /*----------------------------------------------------------------------------------*/

    { nombre: "Opciones", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/Opciones.jpg", url: "Opciones" },
    { nombre: "Nacionales", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/Nacionales.jpg", url: "Nacionales" },
    { nombre: "Infantiles", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/Infantiles.jpg", url: "Infantiles" },
    { nombre: "Cultura", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/Cultura.jpg", url: "Cultura" },
    { nombre: "Mundo", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/Mundo.jpg", url: "Mundo" },
    { nombre: "Cinemas", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/Cinemas.jpg", url: "Cinemas" },
    { nombre: "24x7", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/24x7.jpg", url: "24x7" },
    { nombre: "Deportes", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/Deportes.jpg", url: "Deportes" },
    { nombre: "Musica", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/Musica.jpg", url: "Musica" },
    { nombre: "Religion", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/Religion.jpg", url: "Religion" },
    { nombre: "YTBOeste", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/YTBOeste.jpg", url: "YTBOeste" },
    { nombre: "YTBWars", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/YTBWars.jpg", url: "YTBWars" },
    { nombre: "YTBDocumental", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/YTBDocumental.jpg", url: "YTBDocumental" },
    { nombre: "YTBFantasy", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/YTBFantasy.jpg", url: "YTBFantasy" },
    { nombre: "YTBFiction", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/YTBFiction.jpg", url: "YTBFiction" },
    { nombre: "YTBHorror", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/YTBHorror.jpg", url: "YTBHorror" },
    { nombre: "YTBAnime", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/YTBAnime.jpg", url: "YTBAnime" },
    { nombre: "YTBFamily", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/YTBFamily.jpg", url: "YTBFamily" },
    { nombre: "YTBComedy", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/YTBComedy.jpg", url: "YTBComedy" },
    { nombre: "YTBDrama", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/YTBDrama.jpg", url: "YTBDrama" },
    { nombre: "YTBMusical", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/YTBMusical.jpg", url: "YTBMusical" },
    { nombre: "Series", tipo: "Menu", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/Series.jpg", url: "Series" },

    /*----------------------------------------------------------------------------------*/
    /*-OPCIONES-*/
    /*----------------------------------------------------------------------------------*/
    { nombre: "Activar", tipo: "Opciones", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/activar.jpg", url: "https://tv.teleclub.xyz/activar" },
    { nombre: "Actualizar", tipo: "Opciones", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/actualizar.jpg", url: "/actualizar" },

    /*----------------------------------------------------------------------------------*/
    /*-NACIONALES-*/
    /*----------------------------------------------------------------------------------*/
    { nombre: "TCS +", tipo: "Nacionales", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/tcs.jpg", url: "https://telecorporacion.cdn.vustreams.com/live/19b307cf-3f2d-44cb-bce6-0fd65365c56a/live.isml/live.m3u8" },
    { nombre: "Canal 2", tipo: "Nacionales", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/canal2.jpg", url: "https://telecorporacion-es.cdn.vustreams.com/live/d3e259fa-736d-46b0-b1c9-71caf946ace9/live.isml/d3e259fa-736d-46b0-b1c9-71caf946ace9.m3u8" },
    { nombre: "Canal 3", tipo: "Nacionales", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/canal3.jpg", url: "https://cloud2.streaminglivehd.com:1936/8048/8048/playlist.m3u8" },
    { nombre: "Canal 4", tipo: "Nacionales", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/canal4.jpg", url: "https://telecorporacion-es.cdn.vustreams.com/live/5d245474-cad2-47bc-b605-ad04c619247d/live.isml/live.m3u8" },
    { nombre: "Canal 5", tipo: "Nacionales", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/canal5.jpg", url: "" },
    { nombre: "Canal 6", tipo: "Nacionales", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/canal6.jpg", url: "https://telecorporacion.cdn.vustreams.com/live/b164ebe7-decf-4a5a-8aea-5bb56fb92dfc/live.isml/live.m3u8" },
    { nombre: "Canal 7", tipo: "Nacionales", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/canal7.jpg", url: "https://cdn.elsalvadordigital.com:1936/wowtv/smil:wowtv.smil/playlist.m3u8" },
    { nombre: "Canal 8", tipo: "Nacionales", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/canal8.jpg", url: "http://201.247.102.189/tmp_hls/stream/index.m3u8" },
    { nombre: "Canal 9", tipo: "Nacionales", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/canal9.jpg", url: "https://streaming.asamblea.gob.sv/hls/plenariahd.m3u8" },
    { nombre: "Canal 10", tipo: "Nacionales", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/canal10.jpg", url: "https://5ca3e84a76d30.streamlock.net:443/tves/videotves/playlist.m3u8" },
    { nombre: "Canal 11", tipo: "Nacionales", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/canal11.jpg", url: "https://stream.giostreaming.net:19360/canal11/canal11.m3u8" },
    { nombre: "Canal 12", tipo: "Nacionales", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/canal12.jpg", url: "https://alba-sv-c12-c12.stream.mediatiquestream.com/index.m3u8" },
    { nombre: "Canal 19", tipo: "Nacionales", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/canal19.jpg", url: "https://mgv-channel19.akamaized.net/hls/live/2093190/MGV_CHANNEL19/master.m3u8" },
    { nombre: "Canal 21", tipo: "Nacionales", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/canal21.jpg", url: "https://mgv-channel21.akamaized.net/hls/live/2093191/MGV_CHANNEL21/master.m3u8" },
    { nombre: "Canal 22", tipo: "Nacionales", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/tvmesv.jpg", url: "http://201.247.102.189/tmp_hls/stream/index.m3u8" },

    /*----------------------------------------------------------------------------------*/
    /*-TELECLUB-*/
    /*----------------------------------------------------------------------------------*/
    { inf: "beinsportsextran_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/beinsportsn.jpg", tipo: "Deportes", nombre: "Bein Sports Extra Ñ", url: "http://tv.teleclub.xyz/stream/server_2/deportes/beinsportsextran/master.m3u8" },
    { inf: "directvsports_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/directvsports.jpg", tipo: "Deportes", nombre: "Directv Sports", url: "http://tv.teleclub.xyz/stream/server_2/deportes/directvsports/master.m3u8" },
    { inf: "directvsportsplus_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/directvsports.jpg", tipo: "Deportes", nombre: "Directv Sports +", url: "http://tv.teleclub.xyz/stream/server_2/deportes/directvsportsplus/master.m3u8" },
    { inf: "directvsports2_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/directvsports2.jpg", tipo: "Deportes", nombre: "Directv Sports 2", url: "http://tv.teleclub.xyz/stream/server_2/deportes/directvsports2/master.m3u8" },
    { inf: "espn1_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/espn.jpg", tipo: "Deportes", nombre: "ESPN 1", url: "http://tv.teleclub.xyz/stream/server_2/deportes/espn1/master.m3u8" },
    { inf: "espn2_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/espn2.jpg", tipo: "Deportes", nombre: "ESPN 2", url: "http://tv.teleclub.xyz/stream/server_2/deportes/espn2/master.m3u8" },
    { inf: "espn3_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/espn3.jpg", tipo: "Deportes", nombre: "ESPN 3", url: "http://tv.teleclub.xyz/stream/server_2/deportes/espn3/master.m3u8" },
    { inf: "espn4_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/espn4.jpg", tipo: "Deportes", nombre: "ESPN 4", url: "http://tv.teleclub.xyz/stream/server_2/deportes/espn4/master.m3u8" },
    { inf: "espn5_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/espn.jpg", tipo: "Deportes", nombre: "ESPN 5", url: "http://tv.teleclub.xyz/stream/server_2/deportes/espn5/master.m3u8" },
    { inf: "espnpremium_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/espnpremium.jpg", tipo: "Deportes", nombre: "ESPN Premium", url: "http://tv.teleclub.xyz/stream/server_2/deportes/espnpremium/master.m3u8" },
    { inf: "foxsports1_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/foxsports.jpg", tipo: "Deportes", nombre: "Fox Sports 1", url: "http://tv.teleclub.xyz/stream/server_2/deportes/foxsports1/master.m3u8" },
    { inf: "foxsports1mx_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/foxsports.jpg", tipo: "Deportes", nombre: "Fox Sports 1 MX", url: "http://tv.teleclub.xyz/stream/server_2/deportes/foxsports1mx/master.m3u8" },
    { inf: "foxsports2_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/foxsports2.jpg", tipo: "Deportes", nombre: "Fox Sports 2", url: "http://tv.teleclub.xyz/stream/server_2/deportes/foxsports2/master.m3u8" },
    { inf: "foxsports2mx_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/foxsports2.jpg", tipo: "Deportes", nombre: "Fox Sports 2 MX", url: "http://tv.teleclub.xyz/stream/server_3/deportes/foxsports2mx/master.m3u8" },
    { inf: "foxsports2mx_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/foxsports2.jpg", tipo: "Deportes", nombre: "Fox Sports 2 MX", url: "http://tv.teleclub.xyz/stream/server_2/deportes/foxsports2mx/master.m3u8" },
    { inf: "foxsports3_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/foxsports3.jpg", tipo: "Deportes", nombre: "Fox Sports 3", url: "http://tv.teleclub.xyz/stream/server_2/deportes/foxsports3/master.m3u8" },
    { inf: "foxsports3mx_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/foxsports3.jpg", tipo: "Deportes", nombre: "Fox Sports 3 MX", url: "http://tv.teleclub.xyz/stream/server_2/deportes/foxsports3mx/master.m3u8" },
    { inf: "foxsportspremiummx_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/foxsportspremium.jpg", tipo: "Deportes", nombre: "Fox Sports Premium MX", url: "http://tv.teleclub.xyz/stream/server_2/deportes/foxsportspremiummx/master.m3u8" },
    { inf: "golperu_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/golperu.jpg", tipo: "Deportes", nombre: "Gol Peru", url: "http://tv.teleclub.xyz/stream/server_2/deportes/golperu/master.m3u8" },
    { inf: "goltv_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/goltv.jpg", tipo: "Deportes", nombre: "Gol TV", url: "http://tv.teleclub.xyz/stream/server_2/deportes/goltv/master.m3u8" },
    { inf: "tntsports_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/tntsports.jpg", tipo: "Deportes", nombre: "TNT Sports", url: "http://tv.teleclub.xyz/stream/server_2/deportes/tntsports/master.m3u8" },
    { inf: "tudn_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/tudn.jpg", tipo: "Deportes", nombre: "TUDN", url: "http://tv.teleclub.xyz/stream/server_2/deportes/tudn/master.m3u8" },
    { inf: "tycsports_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/tycsports.jpg", tipo: "Deportes", nombre: "TyC Sports", url: "http://tv.teleclub.xyz/stream/server_2/deportes/tycsports/master.m3u8" },
    { inf: "winsportsplus_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/winsportsplus.jpg", tipo: "Deportes", nombre: "Win Sports Plus", url: "http://tv.teleclub.xyz/stream/server_2/deportes/winsportsplus/master.m3u8" },
    { inf: "cartoonnetwork_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/cartoonnetwork.jpg", tipo: "Infantiles", nombre: "Cartoon Network", url: "http://tv.teleclub.xyz/stream/server_1/infantil/cartoonnetwork/master.m3u8" },
    { inf: "cartoonnetwork_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/cartoonnetwork.jpg", tipo: "Infantiles", nombre: "Cartoon Network", url: "http://tv.teleclub.xyz/stream/server_3/infantil/cartoonnetwork/master.m3u8" },
    { inf: "cartoonito_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/cartoonito.jpg", tipo: "Infantiles", nombre: "Cartoonito", url: "http://tv.teleclub.xyz/stream/server_1/infantil/cartoonito/master.m3u8" },
    { inf: "discoverykids_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/discoverykids.jpg", tipo: "Infantiles", nombre: "Discovery Kids", url: "http://tv.teleclub.xyz/stream/server_1/infantil/discoverykids/master.m3u8" },
    { inf: "disney_channel_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/disneychannel.jpg", tipo: "Infantiles", nombre: "Disney Channel", url: "http://tv.teleclub.xyz/stream/server_1/infantil/disney_channel/master.m3u8" },
    { inf: "disney_jr_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/disneyjr.jpg", tipo: "Infantiles", nombre: "Disney Jr", url: "http://tv.teleclub.xyz/stream/server_1/infantil/disney_jr/master.m3u8" },
    { inf: "energeek_retro_0", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/energeekstream.jpg", tipo: "Infantiles", nombre: "Energeek Retro", url: "http://tv.teleclub.xyz/stream/server_0/infantil/energeek_retro/master.m3u8" },
    { inf: "nick_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/nick.jpg", tipo: "Infantiles", nombre: "Nick", url: "http://tv.teleclub.xyz/stream/server_1/infantil/nick/master.m3u8" },
    { inf: "tooncast_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/tooncast.jpg", tipo: "Infantiles", nombre: "Tooncast", url: "http://tv.teleclub.xyz/stream/server_1/infantil/tooncast/master.m3u8" },
    { inf: "atv_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/atvl.jpg", tipo: "Mundo", nombre: "ATV", url: "http://tv.teleclub.xyz/stream/server_1/mundo/atv/master.m3u8" },
    { inf: "azteca7_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/azteca7.jpg", tipo: "Mundo", nombre: "Azteca 7", url: "http://tv.teleclub.xyz/stream/server_1/mundo/azteca7/master.m3u8" },
    { inf: "aztecauno_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/azteca1.jpg", tipo: "Mundo", nombre: "Azteca Uno", url: "http://tv.teleclub.xyz/stream/server_1/mundo/aztecauno/master.m3u8" },
    { inf: "canal5_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/canal5.jpg", tipo: "Mundo", nombre: "Canal 5", url: "http://tv.teleclub.xyz/stream/server_1/mundo/canal5/master.m3u8" },
    { inf: "canal_e_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/canale.jpg", tipo: "Mundo", nombre: "Canal E!", url: "http://tv.teleclub.xyz/stream/server_1/mundo/canal_e/master.m3u8" },
    { inf: "caracol_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/caracol.jpg", tipo: "Mundo", nombre: "Caracol TV", url: "http://tv.teleclub.xyz/stream/server_1/mundo/caracol/master.m3u8" },
    { inf: "dwchannel_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/dwchannel.jpg", tipo: "Mundo", nombre: "DW Channel", url: "http://tv.teleclub.xyz/stream/server_1/mundo/dwchannel/master.m3u8" },
    { inf: "ecuavisa_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/ecuavisa.jpg", tipo: "Mundo", nombre: "Ecuavisa", url: "http://tv.teleclub.xyz/stream/server_1/mundo/ecuavisa/master.m3u8" },
    { inf: "eltrece_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/trecel.jpg", tipo: "Mundo", nombre: "El Trece", url: "http://tv.teleclub.xyz/stream/server_1/mundo/eltrece/master.m3u8" },
    { inf: "galavision_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/galavson.jpg", tipo: "Mundo", nombre: "Galavisión", url: "http://tv.teleclub.xyz/stream/server_1/mundo/galavision/master.m3u8" },
    { inf: "imagenmx_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/imagentv.jpg", tipo: "Mundo", nombre: "Imagen TV", url: "http://tv.teleclub.xyz/stream/server_1/mundo/imagenmx/master.m3u8" },
    { inf: "lasestrellas_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/lasestrellas.jpg", tipo: "Mundo", nombre: "Las Estrellas", url: "http://tv.teleclub.xyz/stream/server_1/mundo/lasestrellas/master.m3u8" },
    { inf: "latina_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/latinatv.jpg", tipo: "Mundo", nombre: "Latina TV", url: "http://tv.teleclub.xyz/stream/server_1/mundo/latina/master.m3u8" },
    { inf: "pasiones_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/pasiones.jpg", tipo: "Mundo", nombre: "Pasiones", url: "http://tv.teleclub.xyz/stream/server_1/mundo/pasiones/master.m3u8" },
    { inf: "rcn_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/rcn.jpg", tipo: "Mundo", nombre: "RCN", url: "http://tv.teleclub.xyz/stream/server_1/mundo/rcn/master.m3u8" },
    { inf: "rcn_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/rcn.jpg", tipo: "Mundo", nombre: "RCN", url: "http://tv.teleclub.xyz/stream/server_3/mundo/rcn/master.m3u8" },
    { inf: "telefe_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/telefe.jpg", tipo: "Mundo", nombre: "Telefe", url: "http://tv.teleclub.xyz/stream/server_1/mundo/telefe/master.m3u8" },
    { inf: "telemundopuertorico_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/telemundo.jpg", tipo: "Mundo", nombre: "Telemundo Puerto Rico", url: "http://tv.teleclub.xyz/stream/server_1/mundo/telemundopuertorico/master.m3u8" },
    { inf: "tlc_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/tlc.jpg", tipo: "Mundo", nombre: "TLC", url: "http://tv.teleclub.xyz/stream/server_1/mundo/tlc/master.m3u8" },
    { inf: "tlnovelas_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/tlnovelas.jpg", tipo: "Mundo", nombre: "tlnovelas", url: "http://tv.teleclub.xyz/stream/server_3/mundo/tlnovelas/master.m3u8" },
    { inf: "tlnovelas_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/tlnovelas.jpg", tipo: "Mundo", nombre: "tlnovelas", url: "http://tv.teleclub.xyz/stream/server_1/mundo/tlnovelas/master.m3u8" },
    { inf: "unicable_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/unicable.jpg", tipo: "Mundo", nombre: "Unicable", url: "http://tv.teleclub.xyz/stream/server_1/mundo/unicable/master.m3u8" },
    { inf: "univision_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/univision.jpg", tipo: "Mundo", nombre: "Univisión", url: "http://tv.teleclub.xyz/stream/server_1/mundo/univision/master.m3u8" },
    { inf: "willaxtv_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/willaxtv.jpg", tipo: "Mundo", nombre: "Willax TV", url: "http://tv.teleclub.xyz/stream/server_1/mundo/willaxtv/master.m3u8" },
    { inf: "animalplanet_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/animalplanet.jpg", tipo: "Cultura", nombre: "Animal Planet", url: "http://tv.teleclub.xyz/stream/server_1/cultura/animalplanet/master.m3u8" },
    { inf: "discoverychannel_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/discoverychannel.jpg", tipo: "Cultura", nombre: "Discovery Channel", url: "http://tv.teleclub.xyz/stream/server_1/cultura/discoverychannel/master.m3u8" },
    { inf: "discoveryh_h_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/discoveryhh.jpg", tipo: "Cultura", nombre: "Discovery H&H", url: "http://tv.teleclub.xyz/stream/server_1/cultura/discoveryh_h/master.m3u8" },
    { inf: "discoveryscience_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/discoverysci.jpg", tipo: "Cultura", nombre: "Discovery Science", url: "http://tv.teleclub.xyz/stream/server_1/cultura/discoveryscience/master.m3u8" },
    { inf: "discoverytheater_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/discoverytheater.jpg", tipo: "Cultura", nombre: "Discovery Theater", url: "http://tv.teleclub.xyz/stream/server_1/cultura/discoverytheater/master.m3u8" },
    { inf: "discoveryturbo_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/discoveryturbo.jpg", tipo: "Cultura", nombre: "Discovery Turbo", url: "http://tv.teleclub.xyz/stream/server_1/cultura/discoveryturbo/master.m3u8" },
    { inf: "discoveryworld_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/discoveryworld.jpg", tipo: "Cultura", nombre: "Discovery World", url: "http://tv.teleclub.xyz/stream/server_1/cultura/discoveryworld/master.m3u8" },
    { inf: "elgourmet_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/elgourmet.jpg", tipo: "Cultura", nombre: "El Gourmet", url: "http://tv.teleclub.xyz/stream/server_1/cultura/elgourmet/master.m3u8" },
    { inf: "h2_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/h2.jpg", tipo: "Cultura", nombre: "H2", url: "http://tv.teleclub.xyz/stream/server_1/cultura/h2/master.m3u8" },
    { inf: "history_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/history.jpg", tipo: "Cultura", nombre: "History", url: "http://tv.teleclub.xyz/stream/server_1/cultura/history/master.m3u8" },
    { inf: "history_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/history.jpg", tipo: "Cultura", nombre: "History", url: "http://tv.teleclub.xyz/stream/server_3/cultura/history/master.m3u8" },
    { inf: "discoveryid_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/did.jpg", tipo: "Cultura", nombre: "ID", url: "http://tv.teleclub.xyz/stream/server_1/cultura/discoveryid/master.m3u8" },
    { inf: "nationalgeographic_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/natgeo.jpg", tipo: "Cultura", nombre: "National Geographic", url: "http://tv.teleclub.xyz/stream/server_1/cultura/nationalgeographic/master.m3u8" },
    { inf: "a_e_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/ae.jpg", tipo: "Cinemas", nombre: "A&E", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/a_e/master.m3u8" },
    { inf: "amc_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/amc.jpg", tipo: "Cinemas", nombre: "AMC", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/amc/master.m3u8" },
    { inf: "axn_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/axn.jpg", tipo: "Cinemas", nombre: "AXN", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/axn/master.m3u8" },
    { inf: "axn_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/axn.jpg", tipo: "Cinemas", nombre: "AXN", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/axn/master.m3u8" },
    { inf: "cinecanal_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/cinecanal.jpg", tipo: "Cinemas", nombre: "Cinecanal", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/cinecanal/master.m3u8" },
    { inf: "cinecanal_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/cinecanal.jpg", tipo: "Cinemas", nombre: "Cinecanal", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/cinecanal/master.m3u8" },
    { inf: "cinemax_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/cinemax.jpg", tipo: "Cinemas", nombre: "Cinemax", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/cinemax/master.m3u8" },
    { inf: "cinemax_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/cinemax.jpg", tipo: "Cinemas", nombre: "Cinemax", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/cinemax/master.m3u8" },
    { inf: "comedycentral_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/comedycentral.jpg", tipo: "Cinemas", nombre: "Comedy Central", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/comedycentral/master.m3u8" },
    { inf: "depelicula_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/depelicula.jpg", tipo: "Cinemas", nombre: "DePelicula", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/depelicula/master.m3u8" },
    { inf: "dhe_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/dhe.jpg", tipo: "Cinemas", nombre: "DHE", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/dhe/master.m3u8" },
    { inf: "distritocomedia_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/distritocomedia.jpg", tipo: "Cinemas", nombre: "Distrito Comedia", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/distritocomedia/master.m3u8" },
    { inf: "fx_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/fx.jpg", tipo: "Cinemas", nombre: "FX", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/fx/master.m3u8" },
    { inf: "fx_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/fx.jpg", tipo: "Cinemas", nombre: "FX", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/fx/master.m3u8" },
    { inf: "golden_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/golden.jpg", tipo: "Cinemas", nombre: "Golden", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/golden/master.m3u8" },
    { inf: "golden_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/golden.jpg", tipo: "Cinemas", nombre: "Golden", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/golden/master.m3u8" },
    { inf: "goldenedge_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/goldenedge.jpg", tipo: "Cinemas", nombre: "Golden Edge", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/goldenedge/master.m3u8" },
    { inf: "goldenplus_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/golden.jpg", tipo: "Cinemas", nombre: "Golden Plus", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/goldenplus/master.m3u8" },
    { inf: "goldenpremier_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/golden.jpg", tipo: "Cinemas", nombre: "Golden Premier", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/goldenpremier/master.m3u8" },
    { inf: "goldenpremier_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/golden.jpg", tipo: "Cinemas", nombre: "Golden Premier", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/goldenpremier/master.m3u8" },
    { inf: "goldenpremier2_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/golden.jpg", tipo: "Cinemas", nombre: "Golden Premier 2", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/goldenpremier2/master.m3u8" },
    { inf: "HBO_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/hbo.jpg", tipo: "Cinemas", nombre: "HBO", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/HBO/master.m3u8" },
    { inf: "hbo2_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/hbo2.jpg", tipo: "Cinemas", nombre: "HBO 2", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/hbo2/master.m3u8" },
    { inf: "hbo_family_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/hbofamily.jpg", tipo: "Cinemas", nombre: "HBO Family", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/hbo_family/master.m3u8" },
    { inf: "hbosignature_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/hbosigma.jpg", tipo: "Cinemas", nombre: "HBO Signature", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/hbosignature/master.m3u8" },
    { inf: "hboxtreme_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/hboxtreme.jpg", tipo: "Cinemas", nombre: "HBO Xtreme", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/hboxtreme/master.m3u8" },
    { inf: "multipremier_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/multipremier.jpg", tipo: "Cinemas", nombre: "Multipremier", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/multipremier/master.m3u8" },
    { inf: "paramountnetwork_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/paramount.jpg", tipo: "Cinemas", nombre: "Paramount Network", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/paramountnetwork/master.m3u8" },
    { inf: "sony_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/sony.jpg", tipo: "Cinemas", nombre: "Sony", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/sony/master.m3u8" },
    { inf: "sony_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/sony.jpg", tipo: "Cinemas", nombre: "Sony", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/sony/master.m3u8" },
    { inf: "space_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/space.jpg", tipo: "Cinemas", nombre: "Space", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/space/master.m3u8" },
    { inf: "space_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/space.jpg", tipo: "Cinemas", nombre: "Space", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/space/master.m3u8" },
    { inf: "starchannel_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/star.jpg", tipo: "Cinemas", nombre: "Star Channel", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/starchannel/master.m3u8" },
    { inf: "starchannel_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/star.jpg", tipo: "Cinemas", nombre: "Star Channel", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/starchannel/master.m3u8" },
    { inf: "studiouniversal_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/studiouniversal.jpg", tipo: "Cinemas", nombre: "Studio Universal", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/studiouniversal/master.m3u8" },
    { inf: "studiouniversal_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/studiouniversal.jpg", tipo: "Cinemas", nombre: "Studio Universasl", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/studiouniversal/master.m3u8" },
    { inf: "tnt_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/tnt.jpg", tipo: "Cinemas", nombre: "TNT", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/tnt/master.m3u8" },
    { inf: "tntseries_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/tntseries.jpg", tipo: "Cinemas", nombre: "TNT Series", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/tntseries/master.m3u8" },
    { inf: "tntseries_2", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/tntseries.jpg", tipo: "Cinemas", nombre: "TNT Series", url: "http://tv.teleclub.xyz/stream/server_2/entretenimiento/tntseries/master.m3u8" },
    { inf: "universalcinema_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/universalcinema.jpg", tipo: "Cinemas", nombre: "Universal Cinema", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/universalcinema/master.m3u8" },
    { inf: "universalcinema_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/universal_cinema.jpg", tipo: "Cinemas", nombre: "Universal Cinema", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/universalcinema/master.m3u8" },
    { inf: "universaltv_3", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/universal.jpg", tipo: "Cinemas", nombre: "Universal TV", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/universaltv/master.m3u8" },
    { inf: "universaltv_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/universal.jpg", tipo: "Cinemas", nombre: "Universal TV", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/universaltv/master.m3u8" },
    { inf: "usatv_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/usatv.jpg", tipo: "Cinemas", nombre: "USA TV", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/usatv/master.m3u8" },
    { inf: "warnerchannel_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/warnerchannel.jpg", tipo: "Cinemas", nombre: "Warner Channel", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/warnerchannel/master.m3u8" },
    { inf: "mtv_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/mtv.jpg", tipo: "Musica", nombre: "mtv", url: "http://tv.teleclub.xyz/stream/server_1/musica/mtv/master.m3u8" },
    { inf: "telehit_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/telehit.jpg", tipo: "Musica", nombre: "Telehit", url: "http://tv.teleclub.xyz/stream/server_1/musica/telehit/master.m3u8" },
    { inf: "chespirito_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/chespirito.jpg", tipo: "24x7", nombre: "Chespirito", url: "http://tv.teleclub.xyz/stream/server_1/24x7/chespirito/master.m3u8" },
    { inf: "dragonballsuper_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/dragonballsuper.jpg", tipo: "24x7", nombre: "Dragon Ball Super", url: "http://tv.teleclub.xyz/stream/server_1/24x7/dragonballsuper/master.m3u8" },
    { inf: "lossimpsons_1", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/lossimpsons.jpg", tipo: "24x7", nombre: "Los Simpsons", url: "http://tv.teleclub.xyz/stream/server_1/24x7/lossimpsons/master.m3u8" },

    /*----------------------------------------------------------------------------------*/
    /*----------------------------------------------------------------------------------*/
    /*----------------------------------------------------------------------------------*/
    /*----------------------------------------------------------------------------------*/
    /*----------------------------------------------------------------------------------*/

    /*----------------------------------------------------------------------------------*/
    /*-INFANTILES PERSONAL-*/
    /*----------------------------------------------------------------------------------*/
    { nombre: "Locomotion Tv", tipo: "Infantiles", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/locomotiontv.jpg", url: "http://51.222.85.85:81/hls/loco/index.m3u8" },
    { nombre: "Energeek Fan", tipo: "Infantiles", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/energeekfan.jpg", url: "https://xui-backend.energeek.cl/live/10/playlist.m3u8?username=ZZDemoIPTVGH&password=mdo96EuqMkTR" },
    { nombre: "Energeek", tipo: "Infantiles", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/energeek.jpg", url: "https://streaming-cl.sh1ny.space/memfs/e8a8e789-170b-4de4-a33b-90a9a475ce65.m3u8" },
    { nombre: "Ipe Kid", tipo: "Infantiles", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/ipekid.jpg", url: "https://cdnhd.iblups.com/hls/3f2cb1658d114f2693eff18d83199e67.m3u8" },
    { nombre: "Dios Tv Kid", tipo: "Infantiles", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/diostevekids.jpg", url: "https://s.emisoras.tv:8081/diostevekids/index.m3u8" },
    { nombre: "Magic Kid", tipo: "Infantiles", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/magickid.jpg", url: "https://magicstream.ddns.net/magicstream/stream.m3u8" },

    /*----------------------------------------------------------------------------------*/
    /*-CINEMAS PERSONAL-*/
    /*----------------------------------------------------------------------------------*/
    { nombre: "Planeta Tv", tipo: "Cinemas", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/planetatv.jpg", url: "https://live.obslivestream.com/planetatv/index.m3u8?PlaylistM3UCL" },
    { nombre: "Extrema Tv", tipo: "Cinemas", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/extrematv.jpg", url: "https://627bb251f23c7.streamlock.net:444/ExtremaTV/ExtremaTV/playlist.m3u8" },
    { nombre: "Extrema Action", tipo: "Cinemas", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/extremaaction.jpg", url: "https://stmv6.voxtvhd.com.br/cineaccion/cineaccion/playlist.m3u8" },
    { nombre: "Extrema Classic", tipo: "Cinemas", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/extremaclasic.jpg", url: "https://stmv6.voxtvhd.com.br/cineclasico/cineclasico/playlist.m3u8" },
    { nombre: "Peli Mex", tipo: "Cinemas", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/pelimex.jpg", url: "https://amg00658-amg00658c95-canelatv-international-6696.playouts.now.amagi.tv/playlist/amg00658-canelamediafast-pelimexta-canelatvinternational/playlist.m3u8" },
    { nombre: "Runtime Movie", tipo: "Cinemas", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/runtimemovie.jpg", url: "https://stream.ads.ottera.tv/playlist.m3u8?network_id=2649" },
    { nombre: "Cine Friki", tipo: "Cinemas", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/cinefriki.jpg", url: "https://d2jqgm8hyia1n3.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-o8hl8d0bx6aah/index.m3u8" },
    { nombre: "Gringo Tv", tipo: "Cinemas", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/gringotv.jpg", url: "https://amogonetworx-grjngo-2-eu.plex.wurl.tv/playlist.m3u8" },
    { nombre: "Runtime Accion", tipo: "Cinemas", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/runtimeaccion.jpg", url: "https://stream.ads.ottera.tv/cl/250524d0p13jp9qljpoi8hmt6g/854x480_1355200_2_f.m3u8?i=728_6125" },
    { nombre: "Runtime Series", tipo: "Cinemas", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/runtimeseries.jpg", url: "https://stream.ads.ottera.tv/cl/250524d0p15ao9ght782d14hm0/854x480_1355200_2_f.m3u8?i=728_2152" },
    { nombre: "Runtime Clasic", tipo: "Cinemas", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/runtimeclasic.jpg", url: "https://stream.ads.ottera.tv/cl/250524d0p16869us0pbmbsqdj0/854x480_1355200_2_f.m3u8?i=728_3053" },
    { nombre: "Rruntime Comedia", tipo: "Cinemas", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/runtimecomedia.jpg", url: "https://stream.ads.ottera.tv/cl/250524d0p1bn1ugvi6ap6tefu0/854x480_1355200_2_f.m3u8?i=1164_6131" },
    { nombre: "Cine Romance", tipo: "Cinemas", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/romanceesp.jpg", url: "https://amg00658-amg00658c66-canelatv-international-5554.playouts.now.amagi.tv/playlist/amg00658-canelamediafast-cineromanticoappta-canelatvinternational/cb553d177b6c648b9ad43e60d8ef42a4d8243dfc087a8d6933fb4b926bc10f41e2e5af97b20cac7822fb0fdf61146d5a4d009247d8780ad7967cac48240d5734c6cdd52e8be24b4daddd0c2d34b07c0e49857671ad594f32d5e0110dc51ab07a0e1ca1494d5e2082b00cb27751c09e0a957f378bbdbe306f2c180680585ee2be5da5edf55f43d16aa3e0141a882c4db4d45fc8d54abb9d865399429b7ea4179cc3a3da864187849601046688426188adc7f8fa1ba0ff1fddff96290a9d7d3e471a5af4d1eb942c12a7378ed8659db1d24bf001da8165a06d32a9099b4efe43e28a11b3c6932293acb59f714035b2c55f6e35e2a2c86a408f52cf04c89193a1577989f7066c46c468d636247894f88b2785cd55a5b72f93b56d122a8af117d2f5d7f284654b533b2c81e78d622abe8c2029342617d1bb60de3bd47ba981362d637e45a18c54c089cb64fd032589ad51ce1a17b5dac4d6915e7b82571254ec6fce484542f8743d2cab7da2da0b6587705ede7525ad0c7cc063eca820f090dee72d32a1919211a821bce34a9add2a9d40101542bffb275a056b78d3e56944705acb57ebdecfae265a55a2a783ae8e0378343811531e82adb223ccc0937f6f63ab3911697a1418811796388f722e2e1a894f83e2590ec66c470ae9a838515f16e6ebb99388dbcf04f83fe4c6f33d202c4a21da17003565c7b99d539e69132d623c606e9c8415a63c966d6361d35f8b47cf005d17f401549d/183/768x432_1200000/index.m3u8" },
    { nombre: "Cine Sureño", tipo: "Cinemas", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/cinesureño.jpg", url: "https://amg01024-olympusat-cinesureno-ono-ad-h2.amagi.tv/playlist/amg01024-olympusat-cinesureno-ono/cb553d177b6c648b9ad43e60d8ef42a4d8243dfc087a8d6933fb4b926bc10f41e2e5af97b20cac7822fb0fdf61146d5a4d009247d8780ad7967cac48240d5734c6cdd52e8be24b4daddd0c2d34b07c0e49857671ad594f32d5e0110dc51ab07a0e1ca1494d5e2082b00cb27751c09e0a957f378bbdbe306f2c180680585ee2be5da5edf55e4cde6bf5b9494e882c4db3825fc8d54abb9d855b9d449b27a016cc96a1dad0178686c001046688426188adc7f8fa1ba0ff1fddff96290a9d7d3e471a5af4d1eb942c12a7378ed8659db1d24bf001da8165a06d32a9099b4efe43e28a11b3c6932293acb59f714035b2c55f6e35e2a2c86a408f52cf04c89193a1577989f7066c46c468d636247894f88b2785cd55a5b72f93b56d122a8af117d2f5d7f284654b533b2c81e78d622abe8c2029342617d1bb60de3bd47ba981362d637e45a18c54c089cb64fd032589ad51ce1a17b5dac4d6915e7b82571254ec6fce484542f8743d2cab7da2da0b6587705ede7525ad0c7cc063eca820f090dee72d32a1919211a821bce34a9add2a9d40101542bffb275a056b78d3e56944705acb57ebdecfae265a55a2a783ae8e0378343811531e82adb223ccc0937f6f63ab3911697a1418811796388f722e2e1a894f83e2590ec66c470ae9a838515f16e6ebb99388dbcf04f83fe4c6f33d202c4a21da17003565c7b99d539f611f661bbde18aaeeb1c614341bd22a4047ef8dfc743f487c2bd02/94/848x480_1985360/index.m3u8" },

    /*----------------------------------------------------------------------------------*/
    /*-MUNDO PERSONAL-*/
    /*----------------------------------------------------------------------------------*/
    { nombre: "Latina Clasic", tipo: "Mundo", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/latinaclasic.jpg", url: "https://redirector.rudo.video/hls-video/plus226/latina2/latina2.smil/playlist.m3u8" },
    { nombre: "Ciudad Magazine", tipo: "Mundo", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/ciudadmagazine.jpg", url: "https://live-01-07-ciudad.vodgc.net/live-01-07-ciudad.vodgc.net/index.m3u8" },
    { nombre: "ClasicV", tipo: "Mundo", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/clasicv.jpg", url: "https://5eaccbab48461.streamlock.net:1936/8112/8112/playlist.m3u8" },
    { nombre: "13 Reality", tipo: "Mundo", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/13reality.jpg", url: "https://origin.dpsgo.com/ssai/event/g7_JOM0ORki9SR5RKHe-Kw/master.m3u8" },
    { nombre: "13 Series", tipo: "Mundo", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/13series.jpg", url: "https://origin.dpsgo.com/ssai/event/f4TrySe8SoiGF8Lu3EIq1g/master.m3u8" },
    { nombre: "13 Festival", tipo: "Mundo", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/13festival.jpg", url: "https://origin.dpsgo.com/ssai/event/Nftd0fM2SXasfDlRphvUsg/master.m3u8" },
    { nombre: "13 Max", tipo: "Mundo", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/13max.jpg", url: "http://coninfo.net:1935/13maxhd/live13maxtvnuevo/playlist.m3u8" },
    { nombre: "Ciudadela Tv", tipo: "Mundo", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/ciudadelatv.jpg", url: "https://cp.panelchs.com:1936/8096/8096/playlist.m3u8" },

    /*----------------------------------------------------------------------------------*/
    /*-RELIGION PERSONAL-*/
    /*----------------------------------------------------------------------------------*/
    { nombre: "A&R", tipo: "Religion", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/ayr.jpg", url: "http://51.222.9.192:3589/stream/play.m3u8" },
    { nombre: "Avivamiento Tv", tipo: "Religion", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/avivamientotv.jpg", url: "https://ssh101.bozztv.com/ssh101/avivamientotv/playlist.m3u8" },
    { nombre: "ABN Tv", tipo: "Religion", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/abntv.jpg", url: "https://s1.abntelevision.com/avivamientoabr/stream/avivamientohd/avivamientohd/playlist.m3u8" },
    { nombre: "Jesus Tv", tipo: "Religion", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/jesus98.jpg", url: "https://cdn.streamhispanatv.net:3189/live/jesustvlive.m3u8" },
    { nombre: "Cristo Vision", tipo: "Religion", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/cristovision.jpg", url: "https://3a310f6ec721e6b362fcd22772b57f36a2fe6bb2.tabeelcr.com:8080/cristovision31/iptv.m3u8" },
    { nombre: "CTNI Tv", tipo: "Religion", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/ctnitv.jpg", url: "https://video1.getstreamhosting.com:1936/8226/8226/playlist.m3u8" },
    { nombre: "Dios Tv", tipo: "Religion", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/diostv.jpg", url: "https://s.emisoras.tv:8081/diostevetv/index.m3u8" },
    { nombre: "EWTN Tv", tipo: "Religion", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/ewtntv.jpg", url: "https://cdn3.wowza.com/1/SmVrQmZCUXZhVDgz/b3J3MFJv/hls/live/playlist.m3u8" },
    { nombre: "Hosanna Tv", tipo: "Religion", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/hosannatv.jpg", url: "https://1206618505.rsc.cdn77.org/LS-ATL-59020-1/playlist.m3u8" },

    /*----------------------------------------------------------------------------------*/
    /*-DEPORTES PERSONAL-*/
    /*----------------------------------------------------------------------------------*/
    { nombre: "Tigo Sport G", tipo: "Deportes", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/tigosportguate.jpg", url: "https://cnm-tsl.otteravision.com/cnm/tsl/tsl.m3u8" },
    { nombre: "CHV Sport", tipo: "Deportes", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/chvsport.jpg", url: "https://mdstrm.com/live-stream-playlist/6531749eaf244059b3ade17b.m3u8?PlaylistM3UCL" },

    /*----------------------------------------------------------------------------------*/
    /*-MUSICA PERSONAL-*/
    /*----------------------------------------------------------------------------------*/
    { nombre: 'Ctv internacional', tipo: 'Musica', logo: 'https://raw.githubusercontent.com/deswes2021/wtv/main/img/ctvinternacional.png', url: 'https://mediacp.us:8081/ctvhn/index.m3u8' },
    { nombre: 'VM Latino', tipo: 'Musica', logo: 'https://raw.githubusercontent.com/deswes2021/wtv/main/img/vmlatino.png', url: 'https://59ef525c24caa.streamlock.net/vmtv/vmlatino/playlist.m3u8' },
    { nombre: 'Mundo de la Musica TV', tipo: 'Musica', logo: 'https://raw.githubusercontent.com/deswes2021/wtv/main/img/mundodelamusicatv.png', url: 'https://tv.arkeo.cl:1936/mundodelamusica/mundodelamusica/playlist.m3u8?PlaylistM3UCL' },
    { nombre: 'Recuerdos Retro Radio TV', tipo: 'Musica', logo: 'https://raw.githubusercontent.com/deswes2021/wtv/main/img/recuerdosretroradiotv.png', url: 'https://panel.tvstream.cl:1936/8034/8034/playlist.m3u8?PlaylistM3UCL' },
    { nombre: 'Retro Plus TV', tipo: 'Musica', logo: 'https://raw.githubusercontent.com/deswes2021/wtv/main/img/retroplustv.png', url: 'https://tls-cl.cdnz.cl/retroplus16@grupoz.cl_retrolive/live/playlist.m3u8?PlaylistM3UCL' },
    { nombre: 'Retro Plus TV Señal 2', tipo: 'Musica', logo: 'https://raw.githubusercontent.com/deswes2021/wtv/main/img/retroplustvseñal2.png', url: 'https://ssh101.bozztv.com/ssh101/retroplustv2/playlist.m3u8?PlaylistM3UCL' },
    { nombre: 'Ruidos TV', tipo: 'Musica', logo: 'https://raw.githubusercontent.com/deswes2021/wtv/main/img/ruidostv.png', url: 'https://stream.skarnetchile.com:19360/ruidostv/ruidostv.m3u8?PlaylistM3UCL' },
    { nombre: 'Urban TV', tipo: 'Musica', logo: 'https://raw.githubusercontent.com/deswes2021/wtv/main/img/urbantv.png', url: 'https://urbanrevolution.es:8443/live/TV/playlist.m3u8?PlaylistM3UCL' },
    { nombre: 'Cadena Elite | ES', tipo: 'Musica', logo: 'https://raw.githubusercontent.com/deswes2021/wtv/main/img/cadenaelite.png', url: 'https://cloudvideo.servers10.com:8081/8004/index.m3u8?PlaylistM3UCL' },
    { nombre: 'Canal VM Latino | CR', tipo: 'Musica', logo: 'https://raw.githubusercontent.com/deswes2021/wtv/main/img/canalvmlatino.png', url: 'https://59ef525c24caa.streamlock.net/vmtv/vmlatino/playlist.m3u8?PlaylistM3UCL' },

    /*----------------------------------------------------------------------------------*/
    /*-YTBOeste-*/
    /*----------------------------------------------------------------------------------*/
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/porunosdolares.jpg", nombre: "Por unos dolares mas", url: "22LUQT2MuXk.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/elbuenoelmaloyelfeo.jpg", nombre: "El bueno el malo y elfeo", url: "NXVSV4UKz-4.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/elultimopistolero.jpg", nombre: "el ultimo pistolero", url: "IZ_vtx3kC4s.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/lavenganzadefrankjames.jpg", nombre: "Venganza de Frank", url: "_emI0fhXszw.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/barroenlosojos.jpg", nombre: "Barro en los ojos", url: "Q_yYNKUwTc8.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/unmalditoamanecer.jpg", nombre: " Maldito amanecer", url: "-UoUvcu5lGk.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/lamuertenocuentalosdolares.jpg", nombre: "Mmuerte no cuenta dolares", url: "5FA2MXpUMWw.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/lasombradesartana.jpg", nombre: "Sombra de sartana", url: "ycW9U9eQ5Rs.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/masalladelaley.jpg", nombre: "masalladelaley", url: "Uq0ChAeYO5w.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/django.jpg", nombre: "django", url: "PJoIQcBl4QU.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/regresoacasadeunvaquero.jpg", nombre: "regreso del vaquero", url: "fSJmNgkCqks.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/unhombreuncaballounapistola.jpg", nombre: "Hombre caballo pistola", url: "GyoMx-kkWaw.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/los4defortapache.jpg", nombre: "4 de fort apache", url: "QhtmoKK44FQ.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/unagujeroenlafrente.jpg", nombre: "un agujero en la frente", url: "p2xqPYogeIw.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/justiciacalibre45.jpg", nombre: "justicia calibre 45", url: "DzUvg9y5Hac.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/lellamabantrinidad.jpg", nombre: "le llamaban trinidad", url: "ChzXUUU76lg.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/leseguianllamandotrinidad.jpg", nombre: "le seguian llamando trinidad", url: "fMMOFkqGj_0.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/elhombredeladiligencia.jpg", nombre: "hombre de la diligencia", url: "Ez8_j6DDzlQ.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/unvaqueromuertonoesunvaquero.jpg", nombre: "vaquero muerto no es vaquero", url: "raRR1C_YF-8.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/ringovuelveparamatar.jpg", nombre: "ringo vuelve a matar", url: "e_nxEk1G9Kg.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/dueloenelbarro.jpg", nombre: "duelo en el barro", url: "CCGYDkerli0.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/123disparaestavez.jpg", nombre: "123disparaestavez", url: "F7Y2sqi_GXM.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/laleydelahorca.jpg", nombre: "laleydelahorca", url: "jCvCYtlZ49E.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/kidblue.jpg", nombre: "kidblue", url: "ImGL5OyNVJI.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/eljugador.jpg", nombre: "eljugador", url: "c_D4pH73BaE.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/danzaconlobos.jpg", nombre: "danzaconlobos", url: "WGx8LvOsSQ0.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/latumba.jpg", nombre: "latumba", url: "VnpWsNNS0Z4.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/KirkDouglasOeste.jpg", nombre: "KirkDouglasOeste", url: "coIuejnBxFg.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/aliadosimprobables.jpg", nombre: "aliadosimprobables", url: "5YeeIcHEJTo.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/elsheriftraidor.jpg", nombre: "elsheriftraidor", url: "G40EhRUBYQQ.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/sinperdon.jpg", nombre: "sinperdon", url: "aDIZcOSdnfc.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/perrossucios.jpg", nombre: "perrossucios", url: "EE1DNIQ6-go.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/puedesamigo.jpg", nombre: "puedesamigo", url: "iwQIz7_5oOk.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/fueradetiempo.jpg", nombre: "fueradetiempo", url: "qlnIqcw-7Sc.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/trinidadysartana.jpg", nombre: "trinidadysartana", url: "Ej9TvNhZbwk.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/ahorcado.jpg", nombre: "ahorcado", url: "EkcZ96_G254.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/tuverdugo.jpg", nombre: "tuverdugo", url: "bh801UK-kv8.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/sangreenlatierra.jpg", nombre: "sangreenlatierra", url: "1vS_tBbqnIk.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/unacoltenlamanodeldiablo.jpg", nombre: "unacoltenlamanodeldiablo", url: "4pgIObGuCrY.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/quiengritavenganza.jpg", nombre: "quiengritavenganza", url: "MfKAyo-.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/legendbillielnino.jpg", nombre: "legendbillielnino", url: "V56eP9G6698.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/sagitario.jpg", nombre: "sagitario", url: "Y4TuwWW7lRo.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/westernpeligroso.jpg", nombre: "westernpeligroso", url: "3LCZsuQ1Dc0.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/westbrother.jpg", nombre: "westbrother", url: "9jGSejS0mak.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/padremurai.jpg", nombre: "padremurai", url: "ySHHK11NRzg.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/riomaldito.jpg", nombre: "riomaldito", url: "3JgPlDGg4RQ.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/colinadebotas.jpg", nombre: "colinadebotas", url: "UAFo-RkQM3o.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/elborde.jpg", nombre: "elborde", url: "4sVl6R42v54.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/lagranja.jpg", nombre: "lagranja", url: "FRK3_OkTyqs.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/otroladodeley.jpg", nombre: "otroladodeley", url: "fiKg-4XSR3g.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/apachekid.jpg", nombre: "apachekid", url: "A1d2ew6Y-d0.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/elvengador.jpg", nombre: "elvengador", url: "HZnHCu2i6Cc.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/fiebredepradera.jpg", nombre: "", url: "cLpWouaOx8k.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/frankyjessi.jpg", nombre: "frankyjessi", url: "XrC-6BTNjhM.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/malditoinvierno.jpg", nombre: "malditoinvierno", url: "-UoUvcu5lGk.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/duelomortal.jpg", nombre: "duelomortal", url: "cjPkpjqXPN0.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/sinaliento.jpg", nombre: "sinaliento", url: "Me_J3c2VSdA.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/oromaldito.jpg", nombre: "oromaldito", url: "4cgD60meH88.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/loquieromuerto.jpg", nombre: "loquieromuerto", url: "L3CMFyAJP1Y.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/rapidoylamuerte.jpg", nombre: "rapidoylamuerte", url: "eL2Zj_ODvIE.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/venganzaeneloeste.jpg", nombre: "venganzaeneloeste", url: "2sebynsktco.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/eltesorodejessijames.jpg", nombre: "eltesorodejessijames", url: "kDlAI0cScAk.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/mannaja.jpg", nombre: "mannaja", url: "TAixK1I7zUc.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/shriftmandibula.jpg", nombre: "shriftmandibula", url: "aDmW2gJWlKs.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/atravesdelhuracan.jpg", nombre: "atravesdelhuracan", url: "5BPyw9UJvAQ.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/dinamitajoe.jpg", nombre: "dinamitajoe", url: "tQHKf6zXUlM.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/eltirador.jpg", nombre: "eltirador", url: "fH1VGUSS4Ec.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/weslegend.jpg", nombre: "weslegend", url: "z8xorTxs8vo.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/historia2pistolas.jpg", nombre: "historia2pistolas", url: "ZEeUfXQ-O8Q.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/balasthobs.jpg", nombre: "balasthobs", url: "rg-0MJlSFMk.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/vidadepistolero.jpg", nombre: "vidadepistolero", url: "3akhgwkg9aM.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/sinley.jpg", nombre: "sinley", url: "mXdgzs9TZQ4.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/llanerosol.jpg", nombre: "llanerosol", url: "i05brRClB5k.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/5forajidos.jpg", nombre: "5forajidos", url: "nxWSy1UbLRs.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/batalladeearp.jpg", nombre: "batalladeearp", url: "Ockz1-Eg1uA.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/killerkid.jpg", nombre: "killerkid", url: "HgjWsQ2ZXnM.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/alambradadeviolencia.jpg", nombre: "alambradadeviolencia", url: "TFagDpmF4yQ.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/sentencia.jpg", nombre: "sentencia", url: "w-IszlzEfZo.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/rewcazador.jpg", nombre: "rewcazador", url: "s9qpHI2U4yo.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/granmclint.jpg", nombre: "granmclint", url: "kMoZ8YqyIag.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/hickok.jpg", nombre: "hickok", url: "wydC2NxmXA0.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/pistolamaldita.jpg", nombre: "pistolamaldita", url: "BvMfVBdIxc4.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/diezhorcas.jpg", nombre: "diezhorcas", url: "kDzifV2oe4c.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/cazadordedemonios.jpg", nombre: "cazadordedemonios", url: "bje4lTTXVRM.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/rifledeken.jpg", nombre: "rifledeken", url: "m6FYVLjaazU.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/fronteradelsur.jpg", nombre: "fronteradelsur", url: "m72vUx_K92A.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/djangovssartana.jpg", nombre: "djangovssartana", url: "vgdzl-N7vs0.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/filadecruces.jpg", nombre: "filadecruces", url: "x1Q3D7ju2bI.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/venganzaindia.jpg", nombre: "venganzaindia", url: "kwLzgVTG1ik.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/lasjusticieras.jpg", nombre: "lasjusticieras", url: "mYFfJKBJNU4.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/vidacriminal.jpg", nombre: "vidacriminal", url: "Q8pIrvjEsDU.ytb" },
    { tipo: "YTBOeste", logo: "https://raw.githubusercontent.com/deswes2021/wtv/main/img/reveldearizona.jpg", nombre: "reveldearizona", url: "HbOUTU-7Xbg.ytb" },

    /*----------------------------------------------------------------------------------*/
    /*-YTBWars-*/
    /*----------------------------------------------------------------------------------*/
    { nombre: "El Final de la 2° Guerra Mundial", tipo: "YTBDocumental", logo: "https://i.ytimg.com/vi/NNrC3TlKuCc/hqdefault.jpg", url: "NNrC3TlKuCc.ytb" },
    { nombre: "La Muerte del Mayor Ejército Alemán", tipo: "YTBDocumental", logo: "https://i.ytimg.com/vi/MMbXPuksW-g/hqdefault.jpg", url: "MMbXPuksW-g.ytb" },
    { nombre: "La ejecución Karl H Frank", tipo: "YTBDocumental", logo: "https://i.ytimg.com/vi/MXhVgxe0Iks/hqdefault.jpg", url: "MXhVgxe0Iks.ytb" },
    { nombre: "Malvinas", tipo: "YTBDocumental", logo: "https://i.ytimg.com/vi/JEofjadnnyY/hqdefault.jpg", url: "JEofjadnnyY.ytb" },
    { nombre: "June 6, 1944 – The Light of Dawn | History - D-Day - World War II Documentary", tipo: "YTBDocumental", logo: "https://i.ytimg.com/vi/0UJYYkK4d8s/hqdefault.jpg", url: "0UJYYkK4d8s.ytb" },
    { nombre: "La guerra del Golfo Pérsico I", tipo: "YTBDocumental", logo: "https://i.ytimg.com/vi/F3juZQ6cFWs/hqdefault.jpg", url: "F3juZQ6cFWs.ytb" },
    { nombre: "Lugares de la Segunda Guerra", tipo: "YTBDocumental", logo: "https://i.ytimg.com/vi/TLm1ydeU0Mw/hqdefault.jpg", url: "TLm1ydeU0Mw.ytb" },
    { nombre: "El Día D-alemana", tipo: "YTBDocumental", logo: "https://i.ytimg.com/vi/pLUOkuOY1pU/hqdefault.jpg", url: "pLUOkuOY1pU.ytb" },
    { nombre: "Alemania después de Hitler", tipo: "YTBDocumental", logo: "https://i.ytimg.com/vi/mICSORoM0e4/hqdefault.jpg", url: "mICSORoM0e4.ytb" },
    { nombre: "Los Hallazgos-Segunda Guerra", tipo: "YTBDocumental", logo: "https://i.ytimg.com/vi/gwp1ixdc4Q8/hqdefault.jpg", url: "gwp1ixdc4Q8.ytb" },
    { nombre: "Guerra Mundial 1914-1918", tipo: "YTBDocumental", logo: "https://i.ytimg.com/vi/p9q8jkZd4vI/hqdefault.jpg", url: "p9q8jkZd4vI.ytb" },
    { nombre: "Tercera guerra mundial", tipo: "YTBDocumental", logo: "https://i.ytimg.com/vi/O_rytU26jYU/hqdefault.jpg", url: "O_rytU26jYU.ytb" },
    { nombre: "Tercera Guerra Mundial", tipo: "YTBDocumental", logo: "https://i.ytimg.com/vi/QocOZkXGIMc/hqdefault.jpg", url: "QocOZkXGIMc.ytb" },
    { nombre: "Alemania: Conmemora Guerra", tipo: "YTBDocumental", logo: "https://i.ytimg.com/vi/Uvn84GUct78/hqdefault.jpg", url: "Uvn84GUct78.ytb" },
    { nombre: "Guerra: la marabunta", tipo: "YTBDocumental", logo: "https://i.ytimg.com/vi/NJwZ7j5qB3Y/hqdefault.jpg", url: "NJwZ7j5qB3Y.ytb" },
    { nombre: "Cómo Terminó la 1° Guerra", tipo: "YTBDocumental", logo: "https://i.ytimg.com/vi/pREjzJJ08DY/hqdefault.jpg", url: "pREjzJJ08DY.ytb" },
    { nombre: "La Primera Guerra para niños", tipo: "YTBDocumental", logo: "https://i.ytimg.com/vi/MPBRjw7UZYQ/hqdefault.jpg", url: "MPBRjw7UZYQ.ytb" }
    
]
